# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_auto_20170509_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.IntegerField(choices=[(0, 'Aguardando aprovação'), (2, 'Aprovado'), (1, 'Em andamento'), (3, 'Cancelado'), (4, 'Finalizado com sucesso'), (5, 'Finalizado com falha')], default=0, verbose_name='Status'),
        ),
    ]
