# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-24 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0005_auto_20170525_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='cnc_option',
            field=models.IntegerField(choices=[(0, 'Marcação a laser'), (1, 'Corte com fresa')], default=1, verbose_name='Tipo de solicitação'),
        ),
    ]
