# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-24 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import request.models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0006_request_cnc_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='g_code',
            field=models.FileField(blank=True, upload_to=request.models.user_directory_path, validators=[request.models.validate_gcode_file], verbose_name='Arquivo G-code'),
        ),
    ]
