# [START runtime]
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT x_maquina.wsgi

beta_settings:
    cloud_sql_instances: x-maquina:us-east1:xmaquina

runtime_config:
  python_version: 3
# [END runtime]
